# -*- coding: utf-8 -*-
"""CCA(complate-case-analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NSiqOFAiDvxYlKnPHtNzFEW5l--Edd4Q
"""

# cca --- > complete case analysis

# df --- > missing data --- > filter missing data
# new_df = filtered_columns_in_which_we_have_missing data

# new_df -- > missing_data_drop

# Architecture
# past column in which we have missing data
# updated column in which we have no missing data

# if past data architecture is overlap to new data architecture
# it means we can drop missing data .
# if past data architecture is not overlap to new data architecture
# it means we can not drop missing data . we will fill missing data

import pandas as pd
import numpy as np

df = pd.read_csv("/content/dsjob - dsjob.csv")
df.head()

df.isnull().mean()*100

cols = [var for var in df.columns if df[var].isnull().mean() < 0.05 and df[var].isnull().mean() > 0]
cols

df[cols].sample(5)

df['education_level'].value_counts()

len(df[cols].dropna() ) / len(df)

new_df = df[cols].dropna()
df.shape, new_df.shape

import matplotlib.pyplot as plt

fig = plt.figure()
ax = fig.add_subplot(111)

#original data
df['experience'].hist(bins=50, ax=ax, density=True, color='red')

# data after cca, the argument aplha makes the colur transperent, so we can
# see the overplay of the 2 distributions
new_df['experience'].hist(bins=50, ax=ax, color='green', density =True, alpha=0.8)

# titanic data

df = pd.read_csv("/content/titanic - titanic.csv")
df.head()

df.isnull().sum()

df = df.drop(columns=['Fare'],axis= 0)

df = df.drop(columns=['Cabin'])

df.isnull().sum()

df.isnull().mean()*100

cols = [var for var in df.columns if df[var].isnull().mean() < 0.21 and df[var].isnull().mean() > 0]
cols

df[cols].sample(5)

df['Age'].value_counts()

len(df[cols].dropna() ) / len(df)

new_df = df[cols].dropna()
df.shape, new_df.shape

fig = plt.figure()
ax = fig.add_subplot(111)

#original data
df['Age'].hist(bins=50, ax=ax, density=True, color='red')

# data after cca, the argument aplha makes the colur transperent, so we can
# see the overplay of the 2 distributions
new_df['Age'].hist(bins=50, ax=ax, color='green', density =True, alpha=0.8)

# covid data

df = pd.read_csv("/content/covid_toy - covid_toy.csv")
df.head()

df.isnull().sum()

df.isnull().mean()*100

cols = [var for var in df.columns if df[var].isnull().mean() < 0.11 and df[var].isnull().mean() > 0]
cols

df[cols].sample(5)

df['fever'].value_counts()

len(df[cols].dropna() ) / len(df)

new_df = df[cols].dropna()
df.shape, new_df.shape

fig = plt.figure()
ax = fig.add_subplot(111)

#original data
df['fever'].hist(bins=50, ax=ax, density=True, color='red')

# data after cca, the argument aplha makes the colur transperent, so we can
# see the overplay of the 2 distributions
new_df['fever'].hist(bins=50, ax=ax, color='green', density =True, alpha=0.8)

