# -*- coding: utf-8 -*-
"""Encodeing_Types_Practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RHlr7vDs6-gvyKiEII-jxeFv6Qi39oKG
"""

import seaborn as sns
import pandas as pd
import numpy as np

df = sns.load_dataset("tips")

df.head()

# df.isnull().sum()

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder() ##Apporach 1

df['sex']=le.fit_transform(df['sex'])
df['smoker']=le.fit_transform(df['smoker'])
df['day']=le.fit_transform(df['day'])
df['time']=le.fit_transform(df['time'])

df.head(2)

df = sns.load_dataset("tips")
df.head()

df['day'].value_counts()

df = df.drop(columns=['day', 'total_bill', 'tip', 'size' ])  #drop numerical columns

df.head(2)

df_new = df.copy()

from sklearn.preprocessing import OrdinalEncoder ## Apporach 2

oe = OrdinalEncoder(categories = [['Male','Female'],
                                  ['No','Yes'],
                                  ['Dinner','Lunch']])

oe_df = oe.fit_transform(df)

oe_dataframe = pd.DataFrame(oe_df, columns = df_new.columns)

oe_dataframe

df = sns.load_dataset("tips")
df.head()

# cat_cols = df.select_dtypes(include=['object', 'category']).columns

df = df.drop(columns=['total_bill', 'tip', 'size' ])

from sklearn.preprocessing import OneHotEncoder   ## Apporach 3

ohe = OneHotEncoder( drop = 'first', sparse_output= False, dtype = np.int32 )

ohe_df = ohe.fit_transform(df[['sex', 'smoker', 'day', 'time']])

ohe_df

df = pd.DataFrame(ohe_df, columns = df[['sex', 'smoker','day', 'time']]).toarray()  ##problem in convert to dataframe,

df = sns.load_dataset("tips")
df.head()     ## Apporach 4

df = pd.get_dummies(df, columns = ['sex', 'smoker', 'day', 'time'], drop_first =  True)

df = df.astype(int)

df

from sklearn.model_selection import train_test_split

x = df.drop(columns = ['tip'])
y = df['tip']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size =0.2, random_state = 98)

print("Total shape of df :", df.shape)
print('-------------------------------')
print("independent data shape :", x.shape)
print("x_train data shape :", x_train.shape)
print("x_test data shape :",x_test.shape)
print("--------------------------------")
print("Target data shape :", y.shape)
print("y_train data shape :",y_train.shape)
print("y_test data shape :",y_test.shape)

from sklearn.preprocessing import StandardScaler

ss = StandardScaler()

a = ss.fit_transform(x_train)

df = pd.DataFrame(a, columns = x_train.columns)

np.round(df.describe(), 2)

from sklearn.preprocessing import MinMaxScaler

m = MinMaxScaler()

a = m.fit_transform(x_train)

df = pd.DataFrame(a, columns = x_train.columns)

-np.round(df.describe(), 2)

