# -*- coding: utf-8 -*-
"""Encoding_Types.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nHvCS5rUoEUV9B-JEw_FJ_aNaoxg1jIF
"""

# Encoding --- > Transform your categorical data into Numerical data .
# (1). LabelEncoder -- > 1-1 column apply but we cannot set the order manually .
# (2). OrdinalEncoder -- > multi-column apply and we can set the order manually .
# (3). OneHotEncoder --- > has_covid[yes,no]--> 2 column create --> covid_yes, covid_no
# (4). get_dummies --- > has_covid[yes,no]---> 2 columns create ---> column name with values

import pandas as pd
import numpy as np

df = pd.read_csv("/content/covid_toy - covid_toy.csv")

df = df.dropna()

df.drop(columns = ['city'], inplace = True)

# Apporach 1 ---> LabelEncoder

from sklearn.preprocessing import LabelEncoder

lb = LabelEncoder()

df['cough'] = lb.fit_transform(df['cough'])
df['gender'] = lb.fit_transform(df['gender'])
df['has_covid'] = lb.fit_transform(df['has_covid'])

df.head(2)

# Apporach 2 ---> OrdinalEncoder

df = pd.read_csv("/content/covid_toy - covid_toy.csv")
df.head(2)

df = df.dropna()

df = df.drop(columns = ['city', 'age', 'fever'])

# df.head(2)

df_new = df.copy()

from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder( categories= [['Male','Female'],
                                   ['Mild','Strong'],
                                   ['No','Yes']])

oe_df = oe.fit_transform(df)

df_oe = pd.DataFrame(oe_df, columns = df_new.columns)

# df_oe

# Apporach 3 ---> OneHotEncoder

df = pd.read_csv("/content/covid_toy - covid_toy.csv")
df.head(2)

df = df.dropna()

from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder( drop = 'first', sparse_output = False, dtype = np.int32)

ohe.fit_transform(df[['gender','cough', 'city', 'has_covid']])

# gender ---> f
# cough ---> s
# city ---> m,b,k
# # has_covid --> n

# Apporach 4 ---> get.dummmies

df = pd.read_csv("/content/covid_toy - covid_toy.csv")
df.head(2)

df = df.dropna()

df = pd.get_dummies(df, columns = ['gender','cough', 'city', 'has_covid'], drop_first=True)

df = df.astype(int)

df