# -*- coding: utf-8 -*-
"""Function_Transformer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15LbzjW_j02O2nYC1tgfiNUELrSATXV5I
"""

'''what is function transformer in machine learning ?

The Function Transformer is a tool in scikit-learn, a popular
Python library for machine learning, that allows you to apply a
specified function to the input data. The Function Transformer
can be useful for performing custom transformations of input
data in a machine learning pipeline.'''

import numpy as np
from sklearn.preprocessing import FunctionTransformer

# create  a dataset
x = np.array([[1,2],[3,4]])

# define the transformation function
log_transformer = FunctionTransformer(np.log1p)

# apply the transformation to the dataset
x_transformed = log_transformer.transform(x)

# view the transformed data
print(x_transformed)

y = np.array([[1,2],[3,4]])

# define a custom feature engineering function
def squ(X):
  return np.hstack((x, x**2))


# create a functiontransformer to apply the custome function
custom_transformer = FunctionTransformer(squ)

# apply the transformer to the input data
x_transformed = custom_transformer.transform(x)

print(x_transformed)

a = np.arange(21,51)

def even(a):
      a = a[a%2==0]
      return a


# create a functiontransformer to apply the custome function
custom_transformer = FunctionTransformer(squ)

# apply the transformer to the input data
x_transformed = custom_transformer.transform(x)

print(x_transformed)

# create a dataset
X = np.array([[1, 2], [3, 4]])

# define a custom scaling function
def my_scaling(X):
  return X / np.max(X)

# create a FunctionTransformer to apply the custom function
custom_transformer = FunctionTransformer(my_scaling)

# apply the transformer to the input data
X_transformed = custom_transformer.transform(X)

# view the transformed data
print(X_transformed)

import numpy as np
from sklearn.preprocessing import FunctionTransformer

from sklearn.preprocessing import FunctionTransformer
import numpy as np

# create a dataset with missing values
X = np.array([[1, 2], [3, np.nan]])

# define a custom cleaning function
def my_cleaning(X):
      X[np.isnan(X)] = 0
      return X

# create a FunctionTransformer to apply the custom function
custom_transformer = FunctionTransformer(my_cleaning)

# apply the transformer to the input data
X_transformed = custom_transformer.transform(X)

# view the transformed data
print(X_transformed)

import pandas as pd

df = pd.read_csv("/content/insurance - insurance.csv")
df.head()

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['sex']=le.fit_transform(df['sex'])
df['smoker']=le.fit_transform(df['smoker'])
df['region']=le.fit_transform(df['region'])

df.head()

x = df.drop(columns=['charges'])
y = df['charges']

import numpy as np
from sklearn.preprocessing import FunctionTransformer

ft = FunctionTransformer(np.log1p)

a = ft.transform(x)

print(a)

df = pd.read_csv("/content/covid_toy - covid_toy.csv")
df.head()

le = LabelEncoder()

df['gender']=le.fit_transform(df['gender'])
df['cough']=le.fit_transform(df['cough'])
df['city']=le.fit_transform(df['city'])
df['has_covid']=le.fit_transform(df['has_covid'])

df.head()

df.isnull().sum()

df['fever'].fillna(df['fever'].mean(), inplace=True)

x = df.drop(columns=['has_covid'])
y = df['fever']

df.head()

import numpy as np
from sklearn.preprocessing import FunctionTransformer

ft = FunctionTransformer(np.sqrt)

a = ft.transform(x)

print(a)

