# -*- coding: utf-8 -*-
"""One Hot Encoding and column Transform .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T8-kbBswIDG0ksn8l3tjoF9eGwpS5pst
"""

import pandas as pd
import numpy as np

from sklearn.impute import SimpleImputer  ## filling the missing values
from sklearn.preprocessing import OneHotEncoder   ##Encoding

from sklearn.preprocessing import OrdinalEncoder    ##Encoding

df = pd.read_csv('/content/covid_toy - covid_toy.csv')

df.head(2)

df.isnull().sum()

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(df.drop(columns=['has_covid']),
                                                    df['has_covid'], test_size=0.2)

x_train.shape

# adding simple imputer to feaver column
si = SimpleImputer(strategy= 'mean')
x_train_fever = si.fit_transform(x_train[['fever']])

#also the test data
x_test_feaver = si.fit_transform(x_test[['fever']])

x_train_fever.shape

# Ordinal Encoding ---> cough

oe = OrdinalEncoder(categories= [['Mild','Strong']])
x_train_cough = oe.fit_transform(x_train[['cough']])

# also the test data
x_test_cough = oe.fit_transform(x_test[['cough']])

x_train_cough.shape

# OneHotEncoding -- > Gender , city
ohe = OneHotEncoder(drop = 'first' , sparse_output = False )
x_train_gender_city = ohe.fit_transform(x_train[['gender' , 'city']])

# also the test data
x_test_gender_city = ohe. fit_transform(x_test[['gender' , 'city']])

x_train_gender_city. shape

# Extracting Age

x_train_age = x_train.drop(columns =
                           ['gender','fever','cough','city']).values

# also test data
x_test_age = x_test.drop(columns =
                         ['gender','fever','cough','city']).values

x_train_age.shape

x_train_transformed = np.concatenate((x_train_age, x_train_fever,
                                      x_train_gender_city,
                                      x_train_cough), axis = 1)

x_train_transformed.shape

# by the help of column transformer

from sklearn.compose import ColumnTransformer      # this is how to import ColumnTransformer

transformer = ColumnTransformer(transformers=[
                  ('tnf1',SimpleImputer(),['fever']),
# help of SI we
# fill missing values by mean , median , mode .
                  ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]) , ['cough' ]),
# by this process
# we encode our data .
                  ('tnf3',OneHotEncoder(sparse_output=False, drop='first'), ['gender','city' ])],
                  remainder='passthrough' )
# remainder = passthrough == > it means rest all the columns remain same

transformer.fit_transform(x_train).shape

transformer.transform(x_test).shape

df = pd.read_csv("/content/insurance - insurance.csv")

df.head(2)

df['region'].value_counts()

df.isnull().sum()

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(df.drop(columns=['charges']),
                                                    df['charges'], test_size=0.2)

x_train.shape

from sklearn.compose import ColumnTransformer      # this is how to import ColumnTransformer

transformer = ColumnTransformer(transformers=[
                  ('tnf1',OrdinalEncoder(categories=[['male','female']]),['sex']),
# help of SI we
# fill missing values by mean , median , mode .
                  ('tnf2',OrdinalEncoder(categories=[['yes','no']]) , ['smoker' ]),
# by this process
# we encode our data .
                  ('tnf3',OneHotEncoder(sparse_output=False, drop='first'), ['region' ])],
                  remainder='passthrough' )
# remainder = passthrough == > it means rest all the columns remain same

transformer.fit_transform(x_train).shape

transformer.transform(x_test).shape

